spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: orcamento
          uri: lb://ORCAMENTO
          filters:
            - StripPrefix=1
            - name: UserAuthentication
              args:
                headerName: Authorization
          predicates:
            - Path=/orcamento/**
        - id: carro
          uri: lb://CARRO
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                methods: GET, POST
                backoff:
                  initialInterval: 100ms
                  maxInterval: 2s
                  multiplier: 1.5
          predicates:
            - Path=/carro/**
        - id: fabricante
          uri: lb://FABRICANTE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/fabricante/**


eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
server:
  port: 9999